/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pe.view;

import com.pe.piezas.Player;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.GridLayout;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.border.Border;


/**
 *
 * @author User
 */
public class Gui extends javax.swing.JFrame {

    /**
     * Creates new form Gui
     */
    Player jugador1 = new Player("nombre1", "Azul");
    Player jugador2 = new Player("nombre2", "Rojo");
    int turno=1;
    public Gui() {
        initComponents();
        rootPnl.setLayout(new GridLayout(5,5));
        for (int i = 25; i >0 ; i--) {
            String posicion=String.valueOf(i);
            JPanel panel=new JPanel();
            panel.setLayout(new BorderLayout());
            panel.setBackground(new Color (25,25,200));
            panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
            JLabel pos=new JLabel(posicion);
            pos.setForeground(Color.white);
            panel.add(pos, BorderLayout.PAGE_START);
            JPanel fichaPnl =new JPanel();
            fichaPnl.setBackground(new Color (25,25,200));
            panel.add(fichaPnl, BorderLayout.CENTER);
            rootPnl.add(panel);
            
        }
        System.out.println(rootPnl.getComponentCount());
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rootPnl = new javax.swing.JPanel();
        controlsPnl = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout rootPnlLayout = new javax.swing.GroupLayout(rootPnl);
        rootPnl.setLayout(rootPnlLayout);
        rootPnlLayout.setHorizontalGroup(
            rootPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 669, Short.MAX_VALUE)
        );
        rootPnlLayout.setVerticalGroup(
            rootPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );

        getContentPane().add(rootPnl, java.awt.BorderLayout.CENTER);

        jButton2.setText("Lanzar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlsPnlLayout = new javax.swing.GroupLayout(controlsPnl);
        controlsPnl.setLayout(controlsPnlLayout);
        controlsPnlLayout.setHorizontalGroup(
            controlsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlsPnlLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jButton2)
                .addContainerGap(546, Short.MAX_VALUE))
        );
        controlsPnlLayout.setVerticalGroup(
            controlsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controlsPnlLayout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(33, 33, 33))
        );

        getContentPane().add(controlsPnl, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
     
        
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (turno%2==1){
            
           if (turno>2){
               rootPnl.getComponent(25-jugador1.getCasilla()).setBackground(new Color (25,25,200));
           }
           rootPnl.getComponent(25-jugador1.lanzarDado()).setBackground(Color.red);
           
        }else{
            if (turno>2){
               rootPnl.getComponent(25-jugador2.getCasilla()).setBackground(new Color (25,25,200));
           }
          
           rootPnl.getComponent(25-jugador2.lanzarDado()).setBackground(Color.yellow);
        }
        if (jugador1.getCasilla()==25){
            System.out.println("Ganó nombre1");
            jButton2.setEnabled(false);
        }
        if (jugador2.getCasilla()==25){
            System.out.println("Ganó nombre1");
            jButton2.setEnabled(false);

        }
        turno++;
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel controlsPnl;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel rootPnl;
    // End of variables declaration//GEN-END:variables
}
